# Generated by Django 3.2.8 on 2023-03-24 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.IntegerField(choices=[(1, 'FEMENINO'), (2, 'MASCULINO'), (3, 'NO_BINARI0'), (4, 'OTRO')], null=True)),
                ('edad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cede', models.CharField(max_length=200)),
                ('genero', models.IntegerField(choices=[(1, 'FEMENINO'), (2, 'MASCULINO'), (3, 'NO_BINARI0'), (4, 'OTRO')])),
                ('puntos_ganadores', models.IntegerField()),
                ('puntos_perdedores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('wsp', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('inicio_inscripcion', models.DateField()),
                ('fin_inscripcion', models.DateField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('ciudad', models.CharField(max_length=200)),
                ('cupo_maximo_inscripcion', models.IntegerField(null=True)),
                ('puntos', models.IntegerField()),
                ('organizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(null=True)),
                ('jugadores', models.ManyToManyField(max_length=2, to='main.Jugador')),
                ('partido', models.ForeignKey(max_length=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.partido')),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.torneo'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usuario'),
        ),
    ]
