# Generated by Django 3.2.8 on 2023-03-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='usr',
        ),
        migrations.AddField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(default='- ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='email',
            field=models.EmailField(default='- ', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(default='- ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='password',
            field=models.CharField(default='- ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='username',
            field=models.CharField(default='- ', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='wsp',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
