# Generated by Django 3.2.8 on 2023-03-07 17:31

from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('inicio_inscripcion', models.DateField()),
                ('fin_inscripcion', models.DateField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('categorias', models.IntegerField(choices=[(1, 'PRIMERA'), (2, 'SEGUNDA'), (3, 'TERCERA'), (4, 'CUARTA'), (5, 'QUINTA'), (6, 'SEXTA'), (7, 'SEPTIMA'), (8, 'PRINCIPIANTE'), (9, 'NO_CATEGORIZAD')], default=main.utils.Categoria['NO_CATEGORIZAD'])),
                ('cedes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('jugadores', models.ManyToManyField(max_length=2, to='main.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cede', models.CharField(max_length=200)),
                ('genero', models.IntegerField(choices=[(1, 'FEMENINO'), (2, 'MASCULINO'), (3, 'NO_BINARI0'), (4, 'OTRO')])),
                ('puntos', models.IntegerField()),
                ('resultado', models.ManyToManyField(max_length=2, to='main.Resultado')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.torneo')),
            ],
        ),
    ]
