# Generated by Django 3.2.8 on 2023-03-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230324_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(choices=[(1, 'FEMENINO'), (2, 'MASCULINO'), (3, 'NO_BINARI0'), (4, 'OTRO')], null=True),
        ),
    ]
