# Generated by Django 3.2.8 on 2023-03-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230324_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(null=True),
        ),
    ]
