# Generated by Django 3.2.8 on 2023-03-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_partido_resultado_torneo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.torneo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
