# Generated by Django 3.2.8 on 2023-03-20 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230311_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partido',
            old_name='puntos',
            new_name='puntos_ganadores',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='cedes',
        ),
        migrations.AddField(
            model_name='partido',
            name='puntos_perdedores',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='partido',
            field=models.ForeignKey(max_length=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.partido'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='ciudad',
            field=models.CharField(default='lalala', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torneo',
            name='cupo_maximo_inscripcion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='organizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.usuario'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='puntos',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado',
            name='puntos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
