# Generated by Django 3.2.8 on 2023-03-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_usuario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria',
            field=models.IntegerField(null=True),
        ),
    ]
