# Generated by Django 3.2.8 on 2023-03-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usuario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='jugadores',
            field=models.ManyToManyField(max_length=2, to='main.Usuario'),
        ),
    ]
