# Generated by Django 3.2.8 on 2023-03-26 14:49

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_resultado_jugadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='categorias',
            field=django_jsonfield_backport.models.JSONField(default={'cat': [-1]}),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='categoria',
            field=models.IntegerField(default=-1),
        ),
    ]
